version: '3.2'
services:
  math-service: 
    ports:
      - '3007:3007'
    env_file: ./math-service/.env.local
  microservices-consumer:
    ports:
      - '3006:3006'
    env_file: ./microservices-consumer/.env.local
