version: '3.2'
services:
  math-service: 
    ports:
      - '3700:3007'
    env_file: ./math-service/.env.production
    image: DOCKER_HUB_PULL_COMMAND
  microservices-consumer:
    ports:
      - '3600:3006'
    env_file: ./microservices-consumer/.env.production
    image: DOCKER_HUB_PULL_COMMAND
