version: '3.2'
services:
  math-service: 
    build:
      context: ./math-service
      dockerfile: 'Dockerfile'
    ports:
      - '3007:3007'
    env_file: ./math-service/.env.local
    image: math-service
  microservices-consumer:
    build:
      context: ./microservices-consumer
      dockerfile: 'Dockerfile'
    ports:
      - '3006:3006'
    env_file: ./microservices-consumer/.env.local
    image: microservices-consumer
